---
# Source: sveltekit-web3auth-template/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sveltekit-web3auth-template-pr-71-preview-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/CloudNativeEntrepreneur/sveltekit-web3auth-template.git
    targetRevision: renovate/autoprefixer-10.x
    helm:
      version: v3
      values: |
        image:
          tag: pr-71-851b17cb76783ee0571ffb6801904b2df77cf897
  destination:
    namespace: sveltekit-web3auth-template-pr-71-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
# Source: sveltekit-web3auth-template/templates/environment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sveltekit-web3auth-template-pr-71-preview-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: example-preview-envs
  source:
    path: helm
    repoURL: https://github.com/cloudnativeentrepreneur/environment.git
    targetRevision: v0.5.3
    helm:
      version: v3
  destination:
    namespace: sveltekit-web3auth-template-pr-71-preview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
